include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false

linter:
  rules:
    - always_declare_return_types
    - avoid_returning_null_for_future
    - avoid_types_on_closure_parameters
    - await_only_futures
    - prefer_null_aware_operators
    - cancel_subscriptions
    - directives_ordering
    - prefer_single_quotes
    - prefer_relative_imports
    - prefer_typing_uninitialized_variables
    - omit_local_variable_types
    - prefer_final_locals
    - prefer_final_fields
    - camel_case_types
    - prefer_equal_for_default_values